# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/jesd204/layers/axi_ad9144_jesd/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ip/axi_ad9144_jesd_axi_jesd204_tx_0_0/axi_ad9144_jesd_axi_jesd204_tx_0_0.xci
# IP: The module: 'axi_ad9144_jesd_axi_jesd204_tx_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/jesd204/layers/axi_ad9144_jesd/axi_ad9144_jesd.gen/sources_1/bd/axi_ad9144_jesd/ip/axi_ad9144_jesd_axi_jesd204_tx_0_0/axi_jesd204_tx_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9144_jesd_axi_jesd204_tx_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/GitHub/jesd204/layers/axi_ad9144_jesd/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ip/axi_ad9144_jesd_axi_jesd204_tx_0_0/axi_ad9144_jesd_axi_jesd204_tx_0_0.xci
# IP: The module: 'axi_ad9144_jesd_axi_jesd204_tx_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/jesd204/layers/axi_ad9144_jesd/axi_ad9144_jesd.gen/sources_1/bd/axi_ad9144_jesd/ip/axi_ad9144_jesd_axi_jesd204_tx_0_0/axi_jesd204_tx_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9144_jesd_axi_jesd204_tx_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
