# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/GitHub/jesd204/layers/phy_shared/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_util_adxcvr_0_0/phy_shared_util_adxcvr_0_0.xci
# IP: The module: 'phy_shared_util_adxcvr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/jesd204/layers/phy_shared/phy_shared.gen/sources_1/bd/phy_shared/ip/phy_shared_util_adxcvr_0_0/util_adxcvr_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'phy_shared_util_adxcvr_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/GitHub/jesd204/layers/phy_shared/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_util_adxcvr_0_0/phy_shared_util_adxcvr_0_0.xci
# IP: The module: 'phy_shared_util_adxcvr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/jesd204/layers/phy_shared/phy_shared.gen/sources_1/bd/phy_shared/ip/phy_shared_util_adxcvr_0_0/util_adxcvr_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'phy_shared_util_adxcvr_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
