-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2022.2 (win64) Build 3671981 Fri Oct 14 05:00:03 MDT 2022
-- Date        : Thu Nov  7 09:56:25 2024
-- Host        : PSD033 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top phy_shared_axi_adxcvr_0_1 -prefix
--               phy_shared_axi_adxcvr_0_1_ phy_shared_axi_adxcvr_0_1_stub.vhdl
-- Design      : phy_shared_axi_adxcvr_0_1
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu7ev-fbvb900-1-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity phy_shared_axi_adxcvr_0_1 is
  Port ( 
    up_cm_enb_0 : out STD_LOGIC;
    up_cm_addr_0 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_0 : out STD_LOGIC;
    up_cm_wdata_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_0 : in STD_LOGIC;
    up_es_enb_0 : out STD_LOGIC;
    up_es_addr_0 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_0 : out STD_LOGIC;
    up_es_reset_0 : out STD_LOGIC;
    up_es_wdata_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_0 : in STD_LOGIC;
    up_ch_pll_locked_0 : in STD_LOGIC;
    up_ch_rst_0 : out STD_LOGIC;
    up_ch_user_ready_0 : out STD_LOGIC;
    up_ch_rst_done_0 : in STD_LOGIC;
    up_ch_prbsforceerr_0 : out STD_LOGIC;
    up_ch_prbssel_0 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_0 : out STD_LOGIC;
    up_ch_prbserr_0 : in STD_LOGIC;
    up_ch_prbslocked_0 : in STD_LOGIC;
    up_ch_bufstatus_0 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_0 : out STD_LOGIC;
    up_ch_lpm_dfe_n_0 : out STD_LOGIC;
    up_ch_rate_0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_0 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_0 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_0 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_0 : out STD_LOGIC;
    up_ch_addr_0 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_0 : out STD_LOGIC;
    up_ch_wdata_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_0 : in STD_LOGIC;
    up_es_enb_1 : out STD_LOGIC;
    up_es_addr_1 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_1 : out STD_LOGIC;
    up_es_reset_1 : out STD_LOGIC;
    up_es_wdata_1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_1 : in STD_LOGIC;
    up_ch_pll_locked_1 : in STD_LOGIC;
    up_ch_rst_1 : out STD_LOGIC;
    up_ch_user_ready_1 : out STD_LOGIC;
    up_ch_rst_done_1 : in STD_LOGIC;
    up_ch_prbsforceerr_1 : out STD_LOGIC;
    up_ch_prbssel_1 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_1 : out STD_LOGIC;
    up_ch_prbserr_1 : in STD_LOGIC;
    up_ch_prbslocked_1 : in STD_LOGIC;
    up_ch_bufstatus_1 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_1 : out STD_LOGIC;
    up_ch_lpm_dfe_n_1 : out STD_LOGIC;
    up_ch_rate_1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_1 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_1 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_1 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_1 : out STD_LOGIC;
    up_ch_addr_1 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_1 : out STD_LOGIC;
    up_ch_wdata_1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_1 : in STD_LOGIC;
    up_es_enb_2 : out STD_LOGIC;
    up_es_addr_2 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_2 : out STD_LOGIC;
    up_es_reset_2 : out STD_LOGIC;
    up_es_wdata_2 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_2 : in STD_LOGIC;
    up_ch_pll_locked_2 : in STD_LOGIC;
    up_ch_rst_2 : out STD_LOGIC;
    up_ch_user_ready_2 : out STD_LOGIC;
    up_ch_rst_done_2 : in STD_LOGIC;
    up_ch_prbsforceerr_2 : out STD_LOGIC;
    up_ch_prbssel_2 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_2 : out STD_LOGIC;
    up_ch_prbserr_2 : in STD_LOGIC;
    up_ch_prbslocked_2 : in STD_LOGIC;
    up_ch_bufstatus_2 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_2 : out STD_LOGIC;
    up_ch_lpm_dfe_n_2 : out STD_LOGIC;
    up_ch_rate_2 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_2 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_2 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_2 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_2 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_2 : out STD_LOGIC;
    up_ch_addr_2 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_2 : out STD_LOGIC;
    up_ch_wdata_2 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_2 : in STD_LOGIC;
    up_es_enb_3 : out STD_LOGIC;
    up_es_addr_3 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_3 : out STD_LOGIC;
    up_es_reset_3 : out STD_LOGIC;
    up_es_wdata_3 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_3 : in STD_LOGIC;
    up_ch_pll_locked_3 : in STD_LOGIC;
    up_ch_rst_3 : out STD_LOGIC;
    up_ch_user_ready_3 : out STD_LOGIC;
    up_ch_rst_done_3 : in STD_LOGIC;
    up_ch_prbsforceerr_3 : out STD_LOGIC;
    up_ch_prbssel_3 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_3 : out STD_LOGIC;
    up_ch_prbserr_3 : in STD_LOGIC;
    up_ch_prbslocked_3 : in STD_LOGIC;
    up_ch_bufstatus_3 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_3 : out STD_LOGIC;
    up_ch_lpm_dfe_n_3 : out STD_LOGIC;
    up_ch_rate_3 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_3 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_3 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_3 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_3 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_3 : out STD_LOGIC;
    up_ch_addr_3 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_3 : out STD_LOGIC;
    up_ch_wdata_3 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_3 : in STD_LOGIC;
    up_cm_enb_4 : out STD_LOGIC;
    up_cm_addr_4 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_4 : out STD_LOGIC;
    up_cm_wdata_4 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_4 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_4 : in STD_LOGIC;
    up_es_enb_4 : out STD_LOGIC;
    up_es_addr_4 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_4 : out STD_LOGIC;
    up_es_reset_4 : out STD_LOGIC;
    up_es_wdata_4 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_4 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_4 : in STD_LOGIC;
    up_ch_pll_locked_4 : in STD_LOGIC;
    up_ch_rst_4 : out STD_LOGIC;
    up_ch_user_ready_4 : out STD_LOGIC;
    up_ch_rst_done_4 : in STD_LOGIC;
    up_ch_prbsforceerr_4 : out STD_LOGIC;
    up_ch_prbssel_4 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_4 : out STD_LOGIC;
    up_ch_prbserr_4 : in STD_LOGIC;
    up_ch_prbslocked_4 : in STD_LOGIC;
    up_ch_bufstatus_4 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_4 : out STD_LOGIC;
    up_ch_lpm_dfe_n_4 : out STD_LOGIC;
    up_ch_rate_4 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_4 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_4 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_4 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_4 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_4 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_4 : out STD_LOGIC;
    up_ch_addr_4 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_4 : out STD_LOGIC;
    up_ch_wdata_4 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_4 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_4 : in STD_LOGIC;
    up_es_enb_5 : out STD_LOGIC;
    up_es_addr_5 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_5 : out STD_LOGIC;
    up_es_reset_5 : out STD_LOGIC;
    up_es_wdata_5 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_5 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_5 : in STD_LOGIC;
    up_ch_pll_locked_5 : in STD_LOGIC;
    up_ch_rst_5 : out STD_LOGIC;
    up_ch_user_ready_5 : out STD_LOGIC;
    up_ch_rst_done_5 : in STD_LOGIC;
    up_ch_prbsforceerr_5 : out STD_LOGIC;
    up_ch_prbssel_5 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_5 : out STD_LOGIC;
    up_ch_prbserr_5 : in STD_LOGIC;
    up_ch_prbslocked_5 : in STD_LOGIC;
    up_ch_bufstatus_5 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_5 : out STD_LOGIC;
    up_ch_lpm_dfe_n_5 : out STD_LOGIC;
    up_ch_rate_5 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_5 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_5 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_5 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_5 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_5 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_5 : out STD_LOGIC;
    up_ch_addr_5 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_5 : out STD_LOGIC;
    up_ch_wdata_5 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_5 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_5 : in STD_LOGIC;
    up_es_enb_6 : out STD_LOGIC;
    up_es_addr_6 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_6 : out STD_LOGIC;
    up_es_reset_6 : out STD_LOGIC;
    up_es_wdata_6 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_6 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_6 : in STD_LOGIC;
    up_ch_pll_locked_6 : in STD_LOGIC;
    up_ch_rst_6 : out STD_LOGIC;
    up_ch_user_ready_6 : out STD_LOGIC;
    up_ch_rst_done_6 : in STD_LOGIC;
    up_ch_prbsforceerr_6 : out STD_LOGIC;
    up_ch_prbssel_6 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_6 : out STD_LOGIC;
    up_ch_prbserr_6 : in STD_LOGIC;
    up_ch_prbslocked_6 : in STD_LOGIC;
    up_ch_bufstatus_6 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_6 : out STD_LOGIC;
    up_ch_lpm_dfe_n_6 : out STD_LOGIC;
    up_ch_rate_6 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_6 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_6 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_6 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_6 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_6 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_6 : out STD_LOGIC;
    up_ch_addr_6 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_6 : out STD_LOGIC;
    up_ch_wdata_6 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_6 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_6 : in STD_LOGIC;
    up_es_enb_7 : out STD_LOGIC;
    up_es_addr_7 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_7 : out STD_LOGIC;
    up_es_reset_7 : out STD_LOGIC;
    up_es_wdata_7 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_7 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_7 : in STD_LOGIC;
    up_ch_pll_locked_7 : in STD_LOGIC;
    up_ch_rst_7 : out STD_LOGIC;
    up_ch_user_ready_7 : out STD_LOGIC;
    up_ch_rst_done_7 : in STD_LOGIC;
    up_ch_prbsforceerr_7 : out STD_LOGIC;
    up_ch_prbssel_7 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_7 : out STD_LOGIC;
    up_ch_prbserr_7 : in STD_LOGIC;
    up_ch_prbslocked_7 : in STD_LOGIC;
    up_ch_bufstatus_7 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_7 : out STD_LOGIC;
    up_ch_lpm_dfe_n_7 : out STD_LOGIC;
    up_ch_rate_7 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_7 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_7 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_7 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_7 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_7 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_7 : out STD_LOGIC;
    up_ch_addr_7 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_7 : out STD_LOGIC;
    up_ch_wdata_7 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_7 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_7 : in STD_LOGIC;
    up_cm_enb_8 : out STD_LOGIC;
    up_cm_addr_8 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_8 : out STD_LOGIC;
    up_cm_wdata_8 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_8 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_8 : in STD_LOGIC;
    up_es_enb_8 : out STD_LOGIC;
    up_es_addr_8 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_8 : out STD_LOGIC;
    up_es_reset_8 : out STD_LOGIC;
    up_es_wdata_8 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_8 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_8 : in STD_LOGIC;
    up_ch_pll_locked_8 : in STD_LOGIC;
    up_ch_rst_8 : out STD_LOGIC;
    up_ch_user_ready_8 : out STD_LOGIC;
    up_ch_rst_done_8 : in STD_LOGIC;
    up_ch_prbsforceerr_8 : out STD_LOGIC;
    up_ch_prbssel_8 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_8 : out STD_LOGIC;
    up_ch_prbserr_8 : in STD_LOGIC;
    up_ch_prbslocked_8 : in STD_LOGIC;
    up_ch_bufstatus_8 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_8 : out STD_LOGIC;
    up_ch_lpm_dfe_n_8 : out STD_LOGIC;
    up_ch_rate_8 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_8 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_8 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_8 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_8 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_8 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_8 : out STD_LOGIC;
    up_ch_addr_8 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_8 : out STD_LOGIC;
    up_ch_wdata_8 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_8 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_8 : in STD_LOGIC;
    up_es_enb_9 : out STD_LOGIC;
    up_es_addr_9 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_9 : out STD_LOGIC;
    up_es_reset_9 : out STD_LOGIC;
    up_es_wdata_9 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_9 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_9 : in STD_LOGIC;
    up_ch_pll_locked_9 : in STD_LOGIC;
    up_ch_rst_9 : out STD_LOGIC;
    up_ch_user_ready_9 : out STD_LOGIC;
    up_ch_rst_done_9 : in STD_LOGIC;
    up_ch_prbsforceerr_9 : out STD_LOGIC;
    up_ch_prbssel_9 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_9 : out STD_LOGIC;
    up_ch_prbserr_9 : in STD_LOGIC;
    up_ch_prbslocked_9 : in STD_LOGIC;
    up_ch_bufstatus_9 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_9 : out STD_LOGIC;
    up_ch_lpm_dfe_n_9 : out STD_LOGIC;
    up_ch_rate_9 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_9 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_9 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_9 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_9 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_9 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_9 : out STD_LOGIC;
    up_ch_addr_9 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_9 : out STD_LOGIC;
    up_ch_wdata_9 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_9 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_9 : in STD_LOGIC;
    up_es_enb_10 : out STD_LOGIC;
    up_es_addr_10 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_10 : out STD_LOGIC;
    up_es_reset_10 : out STD_LOGIC;
    up_es_wdata_10 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_10 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_10 : in STD_LOGIC;
    up_ch_pll_locked_10 : in STD_LOGIC;
    up_ch_rst_10 : out STD_LOGIC;
    up_ch_user_ready_10 : out STD_LOGIC;
    up_ch_rst_done_10 : in STD_LOGIC;
    up_ch_prbsforceerr_10 : out STD_LOGIC;
    up_ch_prbssel_10 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_10 : out STD_LOGIC;
    up_ch_prbserr_10 : in STD_LOGIC;
    up_ch_prbslocked_10 : in STD_LOGIC;
    up_ch_bufstatus_10 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_10 : out STD_LOGIC;
    up_ch_lpm_dfe_n_10 : out STD_LOGIC;
    up_ch_rate_10 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_10 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_10 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_10 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_10 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_10 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_10 : out STD_LOGIC;
    up_ch_addr_10 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_10 : out STD_LOGIC;
    up_ch_wdata_10 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_10 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_10 : in STD_LOGIC;
    up_es_enb_11 : out STD_LOGIC;
    up_es_addr_11 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_11 : out STD_LOGIC;
    up_es_reset_11 : out STD_LOGIC;
    up_es_wdata_11 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_11 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_11 : in STD_LOGIC;
    up_ch_pll_locked_11 : in STD_LOGIC;
    up_ch_rst_11 : out STD_LOGIC;
    up_ch_user_ready_11 : out STD_LOGIC;
    up_ch_rst_done_11 : in STD_LOGIC;
    up_ch_prbsforceerr_11 : out STD_LOGIC;
    up_ch_prbssel_11 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_11 : out STD_LOGIC;
    up_ch_prbserr_11 : in STD_LOGIC;
    up_ch_prbslocked_11 : in STD_LOGIC;
    up_ch_bufstatus_11 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_11 : out STD_LOGIC;
    up_ch_lpm_dfe_n_11 : out STD_LOGIC;
    up_ch_rate_11 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_11 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_11 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_11 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_11 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_11 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_11 : out STD_LOGIC;
    up_ch_addr_11 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_11 : out STD_LOGIC;
    up_ch_wdata_11 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_11 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_11 : in STD_LOGIC;
    up_cm_enb_12 : out STD_LOGIC;
    up_cm_addr_12 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_12 : out STD_LOGIC;
    up_cm_wdata_12 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_12 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_12 : in STD_LOGIC;
    up_es_enb_12 : out STD_LOGIC;
    up_es_addr_12 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_12 : out STD_LOGIC;
    up_es_reset_12 : out STD_LOGIC;
    up_es_wdata_12 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_12 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_12 : in STD_LOGIC;
    up_ch_pll_locked_12 : in STD_LOGIC;
    up_ch_rst_12 : out STD_LOGIC;
    up_ch_user_ready_12 : out STD_LOGIC;
    up_ch_rst_done_12 : in STD_LOGIC;
    up_ch_prbsforceerr_12 : out STD_LOGIC;
    up_ch_prbssel_12 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_12 : out STD_LOGIC;
    up_ch_prbserr_12 : in STD_LOGIC;
    up_ch_prbslocked_12 : in STD_LOGIC;
    up_ch_bufstatus_12 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_12 : out STD_LOGIC;
    up_ch_lpm_dfe_n_12 : out STD_LOGIC;
    up_ch_rate_12 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_12 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_12 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_12 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_12 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_12 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_12 : out STD_LOGIC;
    up_ch_addr_12 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_12 : out STD_LOGIC;
    up_ch_wdata_12 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_12 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_12 : in STD_LOGIC;
    up_es_enb_13 : out STD_LOGIC;
    up_es_addr_13 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_13 : out STD_LOGIC;
    up_es_reset_13 : out STD_LOGIC;
    up_es_wdata_13 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_13 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_13 : in STD_LOGIC;
    up_ch_pll_locked_13 : in STD_LOGIC;
    up_ch_rst_13 : out STD_LOGIC;
    up_ch_user_ready_13 : out STD_LOGIC;
    up_ch_rst_done_13 : in STD_LOGIC;
    up_ch_prbsforceerr_13 : out STD_LOGIC;
    up_ch_prbssel_13 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_13 : out STD_LOGIC;
    up_ch_prbserr_13 : in STD_LOGIC;
    up_ch_prbslocked_13 : in STD_LOGIC;
    up_ch_bufstatus_13 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_13 : out STD_LOGIC;
    up_ch_lpm_dfe_n_13 : out STD_LOGIC;
    up_ch_rate_13 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_13 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_13 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_13 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_13 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_13 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_13 : out STD_LOGIC;
    up_ch_addr_13 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_13 : out STD_LOGIC;
    up_ch_wdata_13 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_13 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_13 : in STD_LOGIC;
    up_es_enb_14 : out STD_LOGIC;
    up_es_addr_14 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_14 : out STD_LOGIC;
    up_es_reset_14 : out STD_LOGIC;
    up_es_wdata_14 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_14 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_14 : in STD_LOGIC;
    up_ch_pll_locked_14 : in STD_LOGIC;
    up_ch_rst_14 : out STD_LOGIC;
    up_ch_user_ready_14 : out STD_LOGIC;
    up_ch_rst_done_14 : in STD_LOGIC;
    up_ch_prbsforceerr_14 : out STD_LOGIC;
    up_ch_prbssel_14 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_14 : out STD_LOGIC;
    up_ch_prbserr_14 : in STD_LOGIC;
    up_ch_prbslocked_14 : in STD_LOGIC;
    up_ch_bufstatus_14 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_14 : out STD_LOGIC;
    up_ch_lpm_dfe_n_14 : out STD_LOGIC;
    up_ch_rate_14 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_14 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_14 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_14 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_14 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_14 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_14 : out STD_LOGIC;
    up_ch_addr_14 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_14 : out STD_LOGIC;
    up_ch_wdata_14 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_14 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_14 : in STD_LOGIC;
    up_es_enb_15 : out STD_LOGIC;
    up_es_addr_15 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_15 : out STD_LOGIC;
    up_es_reset_15 : out STD_LOGIC;
    up_es_wdata_15 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_15 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_15 : in STD_LOGIC;
    up_ch_pll_locked_15 : in STD_LOGIC;
    up_ch_rst_15 : out STD_LOGIC;
    up_ch_user_ready_15 : out STD_LOGIC;
    up_ch_rst_done_15 : in STD_LOGIC;
    up_ch_prbsforceerr_15 : out STD_LOGIC;
    up_ch_prbssel_15 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_15 : out STD_LOGIC;
    up_ch_prbserr_15 : in STD_LOGIC;
    up_ch_prbslocked_15 : in STD_LOGIC;
    up_ch_bufstatus_15 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_15 : out STD_LOGIC;
    up_ch_lpm_dfe_n_15 : out STD_LOGIC;
    up_ch_rate_15 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_15 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_15 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_15 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_15 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_15 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_15 : out STD_LOGIC;
    up_ch_addr_15 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_15 : out STD_LOGIC;
    up_ch_wdata_15 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_15 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_15 : in STD_LOGIC;
    up_cm_enb_16 : out STD_LOGIC;
    up_cm_addr_16 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_16 : out STD_LOGIC;
    up_cm_wdata_16 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_16 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_16 : in STD_LOGIC;
    up_es_enb_16 : out STD_LOGIC;
    up_es_addr_16 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_16 : out STD_LOGIC;
    up_es_reset_16 : out STD_LOGIC;
    up_es_wdata_16 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_16 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_16 : in STD_LOGIC;
    up_ch_pll_locked_16 : in STD_LOGIC;
    up_ch_rst_16 : out STD_LOGIC;
    up_ch_user_ready_16 : out STD_LOGIC;
    up_ch_rst_done_16 : in STD_LOGIC;
    up_ch_prbsforceerr_16 : out STD_LOGIC;
    up_ch_prbssel_16 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_16 : out STD_LOGIC;
    up_ch_prbserr_16 : in STD_LOGIC;
    up_ch_prbslocked_16 : in STD_LOGIC;
    up_ch_bufstatus_16 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_16 : out STD_LOGIC;
    up_ch_lpm_dfe_n_16 : out STD_LOGIC;
    up_ch_rate_16 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_16 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_16 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_16 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_16 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_16 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_16 : out STD_LOGIC;
    up_ch_addr_16 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_16 : out STD_LOGIC;
    up_ch_wdata_16 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_16 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_16 : in STD_LOGIC;
    up_es_enb_17 : out STD_LOGIC;
    up_es_addr_17 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_17 : out STD_LOGIC;
    up_es_reset_17 : out STD_LOGIC;
    up_es_wdata_17 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_17 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_17 : in STD_LOGIC;
    up_ch_pll_locked_17 : in STD_LOGIC;
    up_ch_rst_17 : out STD_LOGIC;
    up_ch_user_ready_17 : out STD_LOGIC;
    up_ch_rst_done_17 : in STD_LOGIC;
    up_ch_prbsforceerr_17 : out STD_LOGIC;
    up_ch_prbssel_17 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_17 : out STD_LOGIC;
    up_ch_prbserr_17 : in STD_LOGIC;
    up_ch_prbslocked_17 : in STD_LOGIC;
    up_ch_bufstatus_17 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_17 : out STD_LOGIC;
    up_ch_lpm_dfe_n_17 : out STD_LOGIC;
    up_ch_rate_17 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_17 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_17 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_17 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_17 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_17 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_17 : out STD_LOGIC;
    up_ch_addr_17 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_17 : out STD_LOGIC;
    up_ch_wdata_17 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_17 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_17 : in STD_LOGIC;
    up_es_enb_18 : out STD_LOGIC;
    up_es_addr_18 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_18 : out STD_LOGIC;
    up_es_reset_18 : out STD_LOGIC;
    up_es_wdata_18 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_18 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_18 : in STD_LOGIC;
    up_ch_pll_locked_18 : in STD_LOGIC;
    up_ch_rst_18 : out STD_LOGIC;
    up_ch_user_ready_18 : out STD_LOGIC;
    up_ch_rst_done_18 : in STD_LOGIC;
    up_ch_prbsforceerr_18 : out STD_LOGIC;
    up_ch_prbssel_18 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_18 : out STD_LOGIC;
    up_ch_prbserr_18 : in STD_LOGIC;
    up_ch_prbslocked_18 : in STD_LOGIC;
    up_ch_bufstatus_18 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_18 : out STD_LOGIC;
    up_ch_lpm_dfe_n_18 : out STD_LOGIC;
    up_ch_rate_18 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_18 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_18 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_18 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_18 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_18 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_18 : out STD_LOGIC;
    up_ch_addr_18 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_18 : out STD_LOGIC;
    up_ch_wdata_18 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_18 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_18 : in STD_LOGIC;
    up_es_enb_19 : out STD_LOGIC;
    up_es_addr_19 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_19 : out STD_LOGIC;
    up_es_reset_19 : out STD_LOGIC;
    up_es_wdata_19 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_19 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_19 : in STD_LOGIC;
    up_ch_pll_locked_19 : in STD_LOGIC;
    up_ch_rst_19 : out STD_LOGIC;
    up_ch_user_ready_19 : out STD_LOGIC;
    up_ch_rst_done_19 : in STD_LOGIC;
    up_ch_prbsforceerr_19 : out STD_LOGIC;
    up_ch_prbssel_19 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_19 : out STD_LOGIC;
    up_ch_prbserr_19 : in STD_LOGIC;
    up_ch_prbslocked_19 : in STD_LOGIC;
    up_ch_bufstatus_19 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_19 : out STD_LOGIC;
    up_ch_lpm_dfe_n_19 : out STD_LOGIC;
    up_ch_rate_19 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_19 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_19 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_19 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_19 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_19 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_19 : out STD_LOGIC;
    up_ch_addr_19 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_19 : out STD_LOGIC;
    up_ch_wdata_19 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_19 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_19 : in STD_LOGIC;
    up_cm_enb_20 : out STD_LOGIC;
    up_cm_addr_20 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_20 : out STD_LOGIC;
    up_cm_wdata_20 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_20 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_20 : in STD_LOGIC;
    up_es_enb_20 : out STD_LOGIC;
    up_es_addr_20 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_20 : out STD_LOGIC;
    up_es_reset_20 : out STD_LOGIC;
    up_es_wdata_20 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_20 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_20 : in STD_LOGIC;
    up_ch_pll_locked_20 : in STD_LOGIC;
    up_ch_rst_20 : out STD_LOGIC;
    up_ch_user_ready_20 : out STD_LOGIC;
    up_ch_rst_done_20 : in STD_LOGIC;
    up_ch_prbsforceerr_20 : out STD_LOGIC;
    up_ch_prbssel_20 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_20 : out STD_LOGIC;
    up_ch_prbserr_20 : in STD_LOGIC;
    up_ch_prbslocked_20 : in STD_LOGIC;
    up_ch_bufstatus_20 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_20 : out STD_LOGIC;
    up_ch_lpm_dfe_n_20 : out STD_LOGIC;
    up_ch_rate_20 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_20 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_20 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_20 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_20 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_20 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_20 : out STD_LOGIC;
    up_ch_addr_20 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_20 : out STD_LOGIC;
    up_ch_wdata_20 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_20 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_20 : in STD_LOGIC;
    up_es_enb_21 : out STD_LOGIC;
    up_es_addr_21 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_21 : out STD_LOGIC;
    up_es_reset_21 : out STD_LOGIC;
    up_es_wdata_21 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_21 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_21 : in STD_LOGIC;
    up_ch_pll_locked_21 : in STD_LOGIC;
    up_ch_rst_21 : out STD_LOGIC;
    up_ch_user_ready_21 : out STD_LOGIC;
    up_ch_rst_done_21 : in STD_LOGIC;
    up_ch_prbsforceerr_21 : out STD_LOGIC;
    up_ch_prbssel_21 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_21 : out STD_LOGIC;
    up_ch_prbserr_21 : in STD_LOGIC;
    up_ch_prbslocked_21 : in STD_LOGIC;
    up_ch_bufstatus_21 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_21 : out STD_LOGIC;
    up_ch_lpm_dfe_n_21 : out STD_LOGIC;
    up_ch_rate_21 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_21 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_21 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_21 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_21 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_21 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_21 : out STD_LOGIC;
    up_ch_addr_21 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_21 : out STD_LOGIC;
    up_ch_wdata_21 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_21 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_21 : in STD_LOGIC;
    up_es_enb_22 : out STD_LOGIC;
    up_es_addr_22 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_22 : out STD_LOGIC;
    up_es_reset_22 : out STD_LOGIC;
    up_es_wdata_22 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_22 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_22 : in STD_LOGIC;
    up_ch_pll_locked_22 : in STD_LOGIC;
    up_ch_rst_22 : out STD_LOGIC;
    up_ch_user_ready_22 : out STD_LOGIC;
    up_ch_rst_done_22 : in STD_LOGIC;
    up_ch_prbsforceerr_22 : out STD_LOGIC;
    up_ch_prbssel_22 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_22 : out STD_LOGIC;
    up_ch_prbserr_22 : in STD_LOGIC;
    up_ch_prbslocked_22 : in STD_LOGIC;
    up_ch_bufstatus_22 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_22 : out STD_LOGIC;
    up_ch_lpm_dfe_n_22 : out STD_LOGIC;
    up_ch_rate_22 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_22 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_22 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_22 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_22 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_22 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_22 : out STD_LOGIC;
    up_ch_addr_22 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_22 : out STD_LOGIC;
    up_ch_wdata_22 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_22 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_22 : in STD_LOGIC;
    up_es_enb_23 : out STD_LOGIC;
    up_es_addr_23 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_23 : out STD_LOGIC;
    up_es_reset_23 : out STD_LOGIC;
    up_es_wdata_23 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_23 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_23 : in STD_LOGIC;
    up_ch_pll_locked_23 : in STD_LOGIC;
    up_ch_rst_23 : out STD_LOGIC;
    up_ch_user_ready_23 : out STD_LOGIC;
    up_ch_rst_done_23 : in STD_LOGIC;
    up_ch_prbsforceerr_23 : out STD_LOGIC;
    up_ch_prbssel_23 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_23 : out STD_LOGIC;
    up_ch_prbserr_23 : in STD_LOGIC;
    up_ch_prbslocked_23 : in STD_LOGIC;
    up_ch_bufstatus_23 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_23 : out STD_LOGIC;
    up_ch_lpm_dfe_n_23 : out STD_LOGIC;
    up_ch_rate_23 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_23 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_23 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_23 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_23 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_23 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_23 : out STD_LOGIC;
    up_ch_addr_23 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_23 : out STD_LOGIC;
    up_ch_wdata_23 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_23 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_23 : in STD_LOGIC;
    up_cm_enb_24 : out STD_LOGIC;
    up_cm_addr_24 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_24 : out STD_LOGIC;
    up_cm_wdata_24 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_24 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_24 : in STD_LOGIC;
    up_es_enb_24 : out STD_LOGIC;
    up_es_addr_24 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_24 : out STD_LOGIC;
    up_es_reset_24 : out STD_LOGIC;
    up_es_wdata_24 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_24 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_24 : in STD_LOGIC;
    up_ch_pll_locked_24 : in STD_LOGIC;
    up_ch_rst_24 : out STD_LOGIC;
    up_ch_user_ready_24 : out STD_LOGIC;
    up_ch_rst_done_24 : in STD_LOGIC;
    up_ch_prbsforceerr_24 : out STD_LOGIC;
    up_ch_prbssel_24 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_24 : out STD_LOGIC;
    up_ch_prbserr_24 : in STD_LOGIC;
    up_ch_prbslocked_24 : in STD_LOGIC;
    up_ch_bufstatus_24 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_24 : out STD_LOGIC;
    up_ch_lpm_dfe_n_24 : out STD_LOGIC;
    up_ch_rate_24 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_24 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_24 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_24 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_24 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_24 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_24 : out STD_LOGIC;
    up_ch_addr_24 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_24 : out STD_LOGIC;
    up_ch_wdata_24 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_24 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_24 : in STD_LOGIC;
    up_es_enb_25 : out STD_LOGIC;
    up_es_addr_25 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_25 : out STD_LOGIC;
    up_es_reset_25 : out STD_LOGIC;
    up_es_wdata_25 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_25 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_25 : in STD_LOGIC;
    up_ch_pll_locked_25 : in STD_LOGIC;
    up_ch_rst_25 : out STD_LOGIC;
    up_ch_user_ready_25 : out STD_LOGIC;
    up_ch_rst_done_25 : in STD_LOGIC;
    up_ch_prbsforceerr_25 : out STD_LOGIC;
    up_ch_prbssel_25 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_25 : out STD_LOGIC;
    up_ch_prbserr_25 : in STD_LOGIC;
    up_ch_prbslocked_25 : in STD_LOGIC;
    up_ch_bufstatus_25 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_25 : out STD_LOGIC;
    up_ch_lpm_dfe_n_25 : out STD_LOGIC;
    up_ch_rate_25 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_25 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_25 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_25 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_25 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_25 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_25 : out STD_LOGIC;
    up_ch_addr_25 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_25 : out STD_LOGIC;
    up_ch_wdata_25 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_25 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_25 : in STD_LOGIC;
    up_es_enb_26 : out STD_LOGIC;
    up_es_addr_26 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_26 : out STD_LOGIC;
    up_es_reset_26 : out STD_LOGIC;
    up_es_wdata_26 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_26 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_26 : in STD_LOGIC;
    up_ch_pll_locked_26 : in STD_LOGIC;
    up_ch_rst_26 : out STD_LOGIC;
    up_ch_user_ready_26 : out STD_LOGIC;
    up_ch_rst_done_26 : in STD_LOGIC;
    up_ch_prbsforceerr_26 : out STD_LOGIC;
    up_ch_prbssel_26 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_26 : out STD_LOGIC;
    up_ch_prbserr_26 : in STD_LOGIC;
    up_ch_prbslocked_26 : in STD_LOGIC;
    up_ch_bufstatus_26 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_26 : out STD_LOGIC;
    up_ch_lpm_dfe_n_26 : out STD_LOGIC;
    up_ch_rate_26 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_26 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_26 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_26 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_26 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_26 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_26 : out STD_LOGIC;
    up_ch_addr_26 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_26 : out STD_LOGIC;
    up_ch_wdata_26 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_26 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_26 : in STD_LOGIC;
    up_es_enb_27 : out STD_LOGIC;
    up_es_addr_27 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_27 : out STD_LOGIC;
    up_es_reset_27 : out STD_LOGIC;
    up_es_wdata_27 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_27 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_27 : in STD_LOGIC;
    up_ch_pll_locked_27 : in STD_LOGIC;
    up_ch_rst_27 : out STD_LOGIC;
    up_ch_user_ready_27 : out STD_LOGIC;
    up_ch_rst_done_27 : in STD_LOGIC;
    up_ch_prbsforceerr_27 : out STD_LOGIC;
    up_ch_prbssel_27 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_27 : out STD_LOGIC;
    up_ch_prbserr_27 : in STD_LOGIC;
    up_ch_prbslocked_27 : in STD_LOGIC;
    up_ch_bufstatus_27 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_27 : out STD_LOGIC;
    up_ch_lpm_dfe_n_27 : out STD_LOGIC;
    up_ch_rate_27 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_27 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_27 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_27 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_27 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_27 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_27 : out STD_LOGIC;
    up_ch_addr_27 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_27 : out STD_LOGIC;
    up_ch_wdata_27 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_27 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_27 : in STD_LOGIC;
    up_cm_enb_28 : out STD_LOGIC;
    up_cm_addr_28 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_cm_wr_28 : out STD_LOGIC;
    up_cm_wdata_28 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_rdata_28 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_cm_ready_28 : in STD_LOGIC;
    up_es_enb_28 : out STD_LOGIC;
    up_es_addr_28 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_28 : out STD_LOGIC;
    up_es_reset_28 : out STD_LOGIC;
    up_es_wdata_28 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_28 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_28 : in STD_LOGIC;
    up_ch_pll_locked_28 : in STD_LOGIC;
    up_ch_rst_28 : out STD_LOGIC;
    up_ch_user_ready_28 : out STD_LOGIC;
    up_ch_rst_done_28 : in STD_LOGIC;
    up_ch_prbsforceerr_28 : out STD_LOGIC;
    up_ch_prbssel_28 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_28 : out STD_LOGIC;
    up_ch_prbserr_28 : in STD_LOGIC;
    up_ch_prbslocked_28 : in STD_LOGIC;
    up_ch_bufstatus_28 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_28 : out STD_LOGIC;
    up_ch_lpm_dfe_n_28 : out STD_LOGIC;
    up_ch_rate_28 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_28 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_28 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_28 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_28 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_28 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_28 : out STD_LOGIC;
    up_ch_addr_28 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_28 : out STD_LOGIC;
    up_ch_wdata_28 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_28 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_28 : in STD_LOGIC;
    up_es_enb_29 : out STD_LOGIC;
    up_es_addr_29 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_29 : out STD_LOGIC;
    up_es_reset_29 : out STD_LOGIC;
    up_es_wdata_29 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_29 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_29 : in STD_LOGIC;
    up_ch_pll_locked_29 : in STD_LOGIC;
    up_ch_rst_29 : out STD_LOGIC;
    up_ch_user_ready_29 : out STD_LOGIC;
    up_ch_rst_done_29 : in STD_LOGIC;
    up_ch_prbsforceerr_29 : out STD_LOGIC;
    up_ch_prbssel_29 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_29 : out STD_LOGIC;
    up_ch_prbserr_29 : in STD_LOGIC;
    up_ch_prbslocked_29 : in STD_LOGIC;
    up_ch_bufstatus_29 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_29 : out STD_LOGIC;
    up_ch_lpm_dfe_n_29 : out STD_LOGIC;
    up_ch_rate_29 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_29 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_29 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_29 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_29 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_29 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_29 : out STD_LOGIC;
    up_ch_addr_29 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_29 : out STD_LOGIC;
    up_ch_wdata_29 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_29 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_29 : in STD_LOGIC;
    up_es_enb_30 : out STD_LOGIC;
    up_es_addr_30 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_30 : out STD_LOGIC;
    up_es_reset_30 : out STD_LOGIC;
    up_es_wdata_30 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_30 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_30 : in STD_LOGIC;
    up_ch_pll_locked_30 : in STD_LOGIC;
    up_ch_rst_30 : out STD_LOGIC;
    up_ch_user_ready_30 : out STD_LOGIC;
    up_ch_rst_done_30 : in STD_LOGIC;
    up_ch_prbsforceerr_30 : out STD_LOGIC;
    up_ch_prbssel_30 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_30 : out STD_LOGIC;
    up_ch_prbserr_30 : in STD_LOGIC;
    up_ch_prbslocked_30 : in STD_LOGIC;
    up_ch_bufstatus_30 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_30 : out STD_LOGIC;
    up_ch_lpm_dfe_n_30 : out STD_LOGIC;
    up_ch_rate_30 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_30 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_30 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_30 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_30 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_30 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_30 : out STD_LOGIC;
    up_ch_addr_30 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_30 : out STD_LOGIC;
    up_ch_wdata_30 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_30 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_30 : in STD_LOGIC;
    up_es_enb_31 : out STD_LOGIC;
    up_es_addr_31 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_es_wr_31 : out STD_LOGIC;
    up_es_reset_31 : out STD_LOGIC;
    up_es_wdata_31 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_rdata_31 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_es_ready_31 : in STD_LOGIC;
    up_ch_pll_locked_31 : in STD_LOGIC;
    up_ch_rst_31 : out STD_LOGIC;
    up_ch_user_ready_31 : out STD_LOGIC;
    up_ch_rst_done_31 : in STD_LOGIC;
    up_ch_prbsforceerr_31 : out STD_LOGIC;
    up_ch_prbssel_31 : out STD_LOGIC_VECTOR ( 3 downto 0 );
    up_ch_prbscntreset_31 : out STD_LOGIC;
    up_ch_prbserr_31 : in STD_LOGIC;
    up_ch_prbslocked_31 : in STD_LOGIC;
    up_ch_bufstatus_31 : in STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_bufstatus_rst_31 : out STD_LOGIC;
    up_ch_lpm_dfe_n_31 : out STD_LOGIC;
    up_ch_rate_31 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_sys_clk_sel_31 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    up_ch_out_clk_sel_31 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    up_ch_tx_diffctrl_31 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_postcursor_31 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_tx_precursor_31 : out STD_LOGIC_VECTOR ( 4 downto 0 );
    up_ch_enb_31 : out STD_LOGIC;
    up_ch_addr_31 : out STD_LOGIC_VECTOR ( 11 downto 0 );
    up_ch_wr_31 : out STD_LOGIC;
    up_ch_wdata_31 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_rdata_31 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    up_ch_ready_31 : in STD_LOGIC;
    s_axi_aclk : in STD_LOGIC;
    s_axi_aresetn : in STD_LOGIC;
    up_status : out STD_LOGIC;
    up_pll_rst : out STD_LOGIC;
    s_axi_awvalid : in STD_LOGIC;
    s_axi_awaddr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_awready : out STD_LOGIC;
    s_axi_wvalid : in STD_LOGIC;
    s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_wready : out STD_LOGIC;
    s_axi_bvalid : out STD_LOGIC;
    s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_bready : in STD_LOGIC;
    s_axi_arvalid : in STD_LOGIC;
    s_axi_araddr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_arready : out STD_LOGIC;
    s_axi_rvalid : out STD_LOGIC;
    s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_rready : in STD_LOGIC;
    m_axi_awvalid : out STD_LOGIC;
    m_axi_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_awready : in STD_LOGIC;
    m_axi_wvalid : out STD_LOGIC;
    m_axi_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_wready : in STD_LOGIC;
    m_axi_bvalid : in STD_LOGIC;
    m_axi_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_bready : out STD_LOGIC;
    m_axi_arvalid : out STD_LOGIC;
    m_axi_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_arready : in STD_LOGIC;
    m_axi_rvalid : in STD_LOGIC;
    m_axi_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_rready : out STD_LOGIC
  );

end phy_shared_axi_adxcvr_0_1;

architecture stub of phy_shared_axi_adxcvr_0_1 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "up_cm_enb_0,up_cm_addr_0[11:0],up_cm_wr_0,up_cm_wdata_0[15:0],up_cm_rdata_0[15:0],up_cm_ready_0,up_es_enb_0,up_es_addr_0[11:0],up_es_wr_0,up_es_reset_0,up_es_wdata_0[15:0],up_es_rdata_0[15:0],up_es_ready_0,up_ch_pll_locked_0,up_ch_rst_0,up_ch_user_ready_0,up_ch_rst_done_0,up_ch_prbsforceerr_0,up_ch_prbssel_0[3:0],up_ch_prbscntreset_0,up_ch_prbserr_0,up_ch_prbslocked_0,up_ch_bufstatus_0[1:0],up_ch_bufstatus_rst_0,up_ch_lpm_dfe_n_0,up_ch_rate_0[2:0],up_ch_sys_clk_sel_0[1:0],up_ch_out_clk_sel_0[2:0],up_ch_tx_diffctrl_0[4:0],up_ch_tx_postcursor_0[4:0],up_ch_tx_precursor_0[4:0],up_ch_enb_0,up_ch_addr_0[11:0],up_ch_wr_0,up_ch_wdata_0[15:0],up_ch_rdata_0[15:0],up_ch_ready_0,up_es_enb_1,up_es_addr_1[11:0],up_es_wr_1,up_es_reset_1,up_es_wdata_1[15:0],up_es_rdata_1[15:0],up_es_ready_1,up_ch_pll_locked_1,up_ch_rst_1,up_ch_user_ready_1,up_ch_rst_done_1,up_ch_prbsforceerr_1,up_ch_prbssel_1[3:0],up_ch_prbscntreset_1,up_ch_prbserr_1,up_ch_prbslocked_1,up_ch_bufstatus_1[1:0],up_ch_bufstatus_rst_1,up_ch_lpm_dfe_n_1,up_ch_rate_1[2:0],up_ch_sys_clk_sel_1[1:0],up_ch_out_clk_sel_1[2:0],up_ch_tx_diffctrl_1[4:0],up_ch_tx_postcursor_1[4:0],up_ch_tx_precursor_1[4:0],up_ch_enb_1,up_ch_addr_1[11:0],up_ch_wr_1,up_ch_wdata_1[15:0],up_ch_rdata_1[15:0],up_ch_ready_1,up_es_enb_2,up_es_addr_2[11:0],up_es_wr_2,up_es_reset_2,up_es_wdata_2[15:0],up_es_rdata_2[15:0],up_es_ready_2,up_ch_pll_locked_2,up_ch_rst_2,up_ch_user_ready_2,up_ch_rst_done_2,up_ch_prbsforceerr_2,up_ch_prbssel_2[3:0],up_ch_prbscntreset_2,up_ch_prbserr_2,up_ch_prbslocked_2,up_ch_bufstatus_2[1:0],up_ch_bufstatus_rst_2,up_ch_lpm_dfe_n_2,up_ch_rate_2[2:0],up_ch_sys_clk_sel_2[1:0],up_ch_out_clk_sel_2[2:0],up_ch_tx_diffctrl_2[4:0],up_ch_tx_postcursor_2[4:0],up_ch_tx_precursor_2[4:0],up_ch_enb_2,up_ch_addr_2[11:0],up_ch_wr_2,up_ch_wdata_2[15:0],up_ch_rdata_2[15:0],up_ch_ready_2,up_es_enb_3,up_es_addr_3[11:0],up_es_wr_3,up_es_reset_3,up_es_wdata_3[15:0],up_es_rdata_3[15:0],up_es_ready_3,up_ch_pll_locked_3,up_ch_rst_3,up_ch_user_ready_3,up_ch_rst_done_3,up_ch_prbsforceerr_3,up_ch_prbssel_3[3:0],up_ch_prbscntreset_3,up_ch_prbserr_3,up_ch_prbslocked_3,up_ch_bufstatus_3[1:0],up_ch_bufstatus_rst_3,up_ch_lpm_dfe_n_3,up_ch_rate_3[2:0],up_ch_sys_clk_sel_3[1:0],up_ch_out_clk_sel_3[2:0],up_ch_tx_diffctrl_3[4:0],up_ch_tx_postcursor_3[4:0],up_ch_tx_precursor_3[4:0],up_ch_enb_3,up_ch_addr_3[11:0],up_ch_wr_3,up_ch_wdata_3[15:0],up_ch_rdata_3[15:0],up_ch_ready_3,up_cm_enb_4,up_cm_addr_4[11:0],up_cm_wr_4,up_cm_wdata_4[15:0],up_cm_rdata_4[15:0],up_cm_ready_4,up_es_enb_4,up_es_addr_4[11:0],up_es_wr_4,up_es_reset_4,up_es_wdata_4[15:0],up_es_rdata_4[15:0],up_es_ready_4,up_ch_pll_locked_4,up_ch_rst_4,up_ch_user_ready_4,up_ch_rst_done_4,up_ch_prbsforceerr_4,up_ch_prbssel_4[3:0],up_ch_prbscntreset_4,up_ch_prbserr_4,up_ch_prbslocked_4,up_ch_bufstatus_4[1:0],up_ch_bufstatus_rst_4,up_ch_lpm_dfe_n_4,up_ch_rate_4[2:0],up_ch_sys_clk_sel_4[1:0],up_ch_out_clk_sel_4[2:0],up_ch_tx_diffctrl_4[4:0],up_ch_tx_postcursor_4[4:0],up_ch_tx_precursor_4[4:0],up_ch_enb_4,up_ch_addr_4[11:0],up_ch_wr_4,up_ch_wdata_4[15:0],up_ch_rdata_4[15:0],up_ch_ready_4,up_es_enb_5,up_es_addr_5[11:0],up_es_wr_5,up_es_reset_5,up_es_wdata_5[15:0],up_es_rdata_5[15:0],up_es_ready_5,up_ch_pll_locked_5,up_ch_rst_5,up_ch_user_ready_5,up_ch_rst_done_5,up_ch_prbsforceerr_5,up_ch_prbssel_5[3:0],up_ch_prbscntreset_5,up_ch_prbserr_5,up_ch_prbslocked_5,up_ch_bufstatus_5[1:0],up_ch_bufstatus_rst_5,up_ch_lpm_dfe_n_5,up_ch_rate_5[2:0],up_ch_sys_clk_sel_5[1:0],up_ch_out_clk_sel_5[2:0],up_ch_tx_diffctrl_5[4:0],up_ch_tx_postcursor_5[4:0],up_ch_tx_precursor_5[4:0],up_ch_enb_5,up_ch_addr_5[11:0],up_ch_wr_5,up_ch_wdata_5[15:0],up_ch_rdata_5[15:0],up_ch_ready_5,up_es_enb_6,up_es_addr_6[11:0],up_es_wr_6,up_es_reset_6,up_es_wdata_6[15:0],up_es_rdata_6[15:0],up_es_ready_6,up_ch_pll_locked_6,up_ch_rst_6,up_ch_user_ready_6,up_ch_rst_done_6,up_ch_prbsforceerr_6,up_ch_prbssel_6[3:0],up_ch_prbscntreset_6,up_ch_prbserr_6,up_ch_prbslocked_6,up_ch_bufstatus_6[1:0],up_ch_bufstatus_rst_6,up_ch_lpm_dfe_n_6,up_ch_rate_6[2:0],up_ch_sys_clk_sel_6[1:0],up_ch_out_clk_sel_6[2:0],up_ch_tx_diffctrl_6[4:0],up_ch_tx_postcursor_6[4:0],up_ch_tx_precursor_6[4:0],up_ch_enb_6,up_ch_addr_6[11:0],up_ch_wr_6,up_ch_wdata_6[15:0],up_ch_rdata_6[15:0],up_ch_ready_6,up_es_enb_7,up_es_addr_7[11:0],up_es_wr_7,up_es_reset_7,up_es_wdata_7[15:0],up_es_rdata_7[15:0],up_es_ready_7,up_ch_pll_locked_7,up_ch_rst_7,up_ch_user_ready_7,up_ch_rst_done_7,up_ch_prbsforceerr_7,up_ch_prbssel_7[3:0],up_ch_prbscntreset_7,up_ch_prbserr_7,up_ch_prbslocked_7,up_ch_bufstatus_7[1:0],up_ch_bufstatus_rst_7,up_ch_lpm_dfe_n_7,up_ch_rate_7[2:0],up_ch_sys_clk_sel_7[1:0],up_ch_out_clk_sel_7[2:0],up_ch_tx_diffctrl_7[4:0],up_ch_tx_postcursor_7[4:0],up_ch_tx_precursor_7[4:0],up_ch_enb_7,up_ch_addr_7[11:0],up_ch_wr_7,up_ch_wdata_7[15:0],up_ch_rdata_7[15:0],up_ch_ready_7,up_cm_enb_8,up_cm_addr_8[11:0],up_cm_wr_8,up_cm_wdata_8[15:0],up_cm_rdata_8[15:0],up_cm_ready_8,up_es_enb_8,up_es_addr_8[11:0],up_es_wr_8,up_es_reset_8,up_es_wdata_8[15:0],up_es_rdata_8[15:0],up_es_ready_8,up_ch_pll_locked_8,up_ch_rst_8,up_ch_user_ready_8,up_ch_rst_done_8,up_ch_prbsforceerr_8,up_ch_prbssel_8[3:0],up_ch_prbscntreset_8,up_ch_prbserr_8,up_ch_prbslocked_8,up_ch_bufstatus_8[1:0],up_ch_bufstatus_rst_8,up_ch_lpm_dfe_n_8,up_ch_rate_8[2:0],up_ch_sys_clk_sel_8[1:0],up_ch_out_clk_sel_8[2:0],up_ch_tx_diffctrl_8[4:0],up_ch_tx_postcursor_8[4:0],up_ch_tx_precursor_8[4:0],up_ch_enb_8,up_ch_addr_8[11:0],up_ch_wr_8,up_ch_wdata_8[15:0],up_ch_rdata_8[15:0],up_ch_ready_8,up_es_enb_9,up_es_addr_9[11:0],up_es_wr_9,up_es_reset_9,up_es_wdata_9[15:0],up_es_rdata_9[15:0],up_es_ready_9,up_ch_pll_locked_9,up_ch_rst_9,up_ch_user_ready_9,up_ch_rst_done_9,up_ch_prbsforceerr_9,up_ch_prbssel_9[3:0],up_ch_prbscntreset_9,up_ch_prbserr_9,up_ch_prbslocked_9,up_ch_bufstatus_9[1:0],up_ch_bufstatus_rst_9,up_ch_lpm_dfe_n_9,up_ch_rate_9[2:0],up_ch_sys_clk_sel_9[1:0],up_ch_out_clk_sel_9[2:0],up_ch_tx_diffctrl_9[4:0],up_ch_tx_postcursor_9[4:0],up_ch_tx_precursor_9[4:0],up_ch_enb_9,up_ch_addr_9[11:0],up_ch_wr_9,up_ch_wdata_9[15:0],up_ch_rdata_9[15:0],up_ch_ready_9,up_es_enb_10,up_es_addr_10[11:0],up_es_wr_10,up_es_reset_10,up_es_wdata_10[15:0],up_es_rdata_10[15:0],up_es_ready_10,up_ch_pll_locked_10,up_ch_rst_10,up_ch_user_ready_10,up_ch_rst_done_10,up_ch_prbsforceerr_10,up_ch_prbssel_10[3:0],up_ch_prbscntreset_10,up_ch_prbserr_10,up_ch_prbslocked_10,up_ch_bufstatus_10[1:0],up_ch_bufstatus_rst_10,up_ch_lpm_dfe_n_10,up_ch_rate_10[2:0],up_ch_sys_clk_sel_10[1:0],up_ch_out_clk_sel_10[2:0],up_ch_tx_diffctrl_10[4:0],up_ch_tx_postcursor_10[4:0],up_ch_tx_precursor_10[4:0],up_ch_enb_10,up_ch_addr_10[11:0],up_ch_wr_10,up_ch_wdata_10[15:0],up_ch_rdata_10[15:0],up_ch_ready_10,up_es_enb_11,up_es_addr_11[11:0],up_es_wr_11,up_es_reset_11,up_es_wdata_11[15:0],up_es_rdata_11[15:0],up_es_ready_11,up_ch_pll_locked_11,up_ch_rst_11,up_ch_user_ready_11,up_ch_rst_done_11,up_ch_prbsforceerr_11,up_ch_prbssel_11[3:0],up_ch_prbscntreset_11,up_ch_prbserr_11,up_ch_prbslocked_11,up_ch_bufstatus_11[1:0],up_ch_bufstatus_rst_11,up_ch_lpm_dfe_n_11,up_ch_rate_11[2:0],up_ch_sys_clk_sel_11[1:0],up_ch_out_clk_sel_11[2:0],up_ch_tx_diffctrl_11[4:0],up_ch_tx_postcursor_11[4:0],up_ch_tx_precursor_11[4:0],up_ch_enb_11,up_ch_addr_11[11:0],up_ch_wr_11,up_ch_wdata_11[15:0],up_ch_rdata_11[15:0],up_ch_ready_11,up_cm_enb_12,up_cm_addr_12[11:0],up_cm_wr_12,up_cm_wdata_12[15:0],up_cm_rdata_12[15:0],up_cm_ready_12,up_es_enb_12,up_es_addr_12[11:0],up_es_wr_12,up_es_reset_12,up_es_wdata_12[15:0],up_es_rdata_12[15:0],up_es_ready_12,up_ch_pll_locked_12,up_ch_rst_12,up_ch_user_ready_12,up_ch_rst_done_12,up_ch_prbsforceerr_12,up_ch_prbssel_12[3:0],up_ch_prbscntreset_12,up_ch_prbserr_12,up_ch_prbslocked_12,up_ch_bufstatus_12[1:0],up_ch_bufstatus_rst_12,up_ch_lpm_dfe_n_12,up_ch_rate_12[2:0],up_ch_sys_clk_sel_12[1:0],up_ch_out_clk_sel_12[2:0],up_ch_tx_diffctrl_12[4:0],up_ch_tx_postcursor_12[4:0],up_ch_tx_precursor_12[4:0],up_ch_enb_12,up_ch_addr_12[11:0],up_ch_wr_12,up_ch_wdata_12[15:0],up_ch_rdata_12[15:0],up_ch_ready_12,up_es_enb_13,up_es_addr_13[11:0],up_es_wr_13,up_es_reset_13,up_es_wdata_13[15:0],up_es_rdata_13[15:0],up_es_ready_13,up_ch_pll_locked_13,up_ch_rst_13,up_ch_user_ready_13,up_ch_rst_done_13,up_ch_prbsforceerr_13,up_ch_prbssel_13[3:0],up_ch_prbscntreset_13,up_ch_prbserr_13,up_ch_prbslocked_13,up_ch_bufstatus_13[1:0],up_ch_bufstatus_rst_13,up_ch_lpm_dfe_n_13,up_ch_rate_13[2:0],up_ch_sys_clk_sel_13[1:0],up_ch_out_clk_sel_13[2:0],up_ch_tx_diffctrl_13[4:0],up_ch_tx_postcursor_13[4:0],up_ch_tx_precursor_13[4:0],up_ch_enb_13,up_ch_addr_13[11:0],up_ch_wr_13,up_ch_wdata_13[15:0],up_ch_rdata_13[15:0],up_ch_ready_13,up_es_enb_14,up_es_addr_14[11:0],up_es_wr_14,up_es_reset_14,up_es_wdata_14[15:0],up_es_rdata_14[15:0],up_es_ready_14,up_ch_pll_locked_14,up_ch_rst_14,up_ch_user_ready_14,up_ch_rst_done_14,up_ch_prbsforceerr_14,up_ch_prbssel_14[3:0],up_ch_prbscntreset_14,up_ch_prbserr_14,up_ch_prbslocked_14,up_ch_bufstatus_14[1:0],up_ch_bufstatus_rst_14,up_ch_lpm_dfe_n_14,up_ch_rate_14[2:0],up_ch_sys_clk_sel_14[1:0],up_ch_out_clk_sel_14[2:0],up_ch_tx_diffctrl_14[4:0],up_ch_tx_postcursor_14[4:0],up_ch_tx_precursor_14[4:0],up_ch_enb_14,up_ch_addr_14[11:0],up_ch_wr_14,up_ch_wdata_14[15:0],up_ch_rdata_14[15:0],up_ch_ready_14,up_es_enb_15,up_es_addr_15[11:0],up_es_wr_15,up_es_reset_15,up_es_wdata_15[15:0],up_es_rdata_15[15:0],up_es_ready_15,up_ch_pll_locked_15,up_ch_rst_15,up_ch_user_ready_15,up_ch_rst_done_15,up_ch_prbsforceerr_15,up_ch_prbssel_15[3:0],up_ch_prbscntreset_15,up_ch_prbserr_15,up_ch_prbslocked_15,up_ch_bufstatus_15[1:0],up_ch_bufstatus_rst_15,up_ch_lpm_dfe_n_15,up_ch_rate_15[2:0],up_ch_sys_clk_sel_15[1:0],up_ch_out_clk_sel_15[2:0],up_ch_tx_diffctrl_15[4:0],up_ch_tx_postcursor_15[4:0],up_ch_tx_precursor_15[4:0],up_ch_enb_15,up_ch_addr_15[11:0],up_ch_wr_15,up_ch_wdata_15[15:0],up_ch_rdata_15[15:0],up_ch_ready_15,up_cm_enb_16,up_cm_addr_16[11:0],up_cm_wr_16,up_cm_wdata_16[15:0],up_cm_rdata_16[15:0],up_cm_ready_16,up_es_enb_16,up_es_addr_16[11:0],up_es_wr_16,up_es_reset_16,up_es_wdata_16[15:0],up_es_rdata_16[15:0],up_es_ready_16,up_ch_pll_locked_16,up_ch_rst_16,up_ch_user_ready_16,up_ch_rst_done_16,up_ch_prbsforceerr_16,up_ch_prbssel_16[3:0],up_ch_prbscntreset_16,up_ch_prbserr_16,up_ch_prbslocked_16,up_ch_bufstatus_16[1:0],up_ch_bufstatus_rst_16,up_ch_lpm_dfe_n_16,up_ch_rate_16[2:0],up_ch_sys_clk_sel_16[1:0],up_ch_out_clk_sel_16[2:0],up_ch_tx_diffctrl_16[4:0],up_ch_tx_postcursor_16[4:0],up_ch_tx_precursor_16[4:0],up_ch_enb_16,up_ch_addr_16[11:0],up_ch_wr_16,up_ch_wdata_16[15:0],up_ch_rdata_16[15:0],up_ch_ready_16,up_es_enb_17,up_es_addr_17[11:0],up_es_wr_17,up_es_reset_17,up_es_wdata_17[15:0],up_es_rdata_17[15:0],up_es_ready_17,up_ch_pll_locked_17,up_ch_rst_17,up_ch_user_ready_17,up_ch_rst_done_17,up_ch_prbsforceerr_17,up_ch_prbssel_17[3:0],up_ch_prbscntreset_17,up_ch_prbserr_17,up_ch_prbslocked_17,up_ch_bufstatus_17[1:0],up_ch_bufstatus_rst_17,up_ch_lpm_dfe_n_17,up_ch_rate_17[2:0],up_ch_sys_clk_sel_17[1:0],up_ch_out_clk_sel_17[2:0],up_ch_tx_diffctrl_17[4:0],up_ch_tx_postcursor_17[4:0],up_ch_tx_precursor_17[4:0],up_ch_enb_17,up_ch_addr_17[11:0],up_ch_wr_17,up_ch_wdata_17[15:0],up_ch_rdata_17[15:0],up_ch_ready_17,up_es_enb_18,up_es_addr_18[11:0],up_es_wr_18,up_es_reset_18,up_es_wdata_18[15:0],up_es_rdata_18[15:0],up_es_ready_18,up_ch_pll_locked_18,up_ch_rst_18,up_ch_user_ready_18,up_ch_rst_done_18,up_ch_prbsforceerr_18,up_ch_prbssel_18[3:0],up_ch_prbscntreset_18,up_ch_prbserr_18,up_ch_prbslocked_18,up_ch_bufstatus_18[1:0],up_ch_bufstatus_rst_18,up_ch_lpm_dfe_n_18,up_ch_rate_18[2:0],up_ch_sys_clk_sel_18[1:0],up_ch_out_clk_sel_18[2:0],up_ch_tx_diffctrl_18[4:0],up_ch_tx_postcursor_18[4:0],up_ch_tx_precursor_18[4:0],up_ch_enb_18,up_ch_addr_18[11:0],up_ch_wr_18,up_ch_wdata_18[15:0],up_ch_rdata_18[15:0],up_ch_ready_18,up_es_enb_19,up_es_addr_19[11:0],up_es_wr_19,up_es_reset_19,up_es_wdata_19[15:0],up_es_rdata_19[15:0],up_es_ready_19,up_ch_pll_locked_19,up_ch_rst_19,up_ch_user_ready_19,up_ch_rst_done_19,up_ch_prbsforceerr_19,up_ch_prbssel_19[3:0],up_ch_prbscntreset_19,up_ch_prbserr_19,up_ch_prbslocked_19,up_ch_bufstatus_19[1:0],up_ch_bufstatus_rst_19,up_ch_lpm_dfe_n_19,up_ch_rate_19[2:0],up_ch_sys_clk_sel_19[1:0],up_ch_out_clk_sel_19[2:0],up_ch_tx_diffctrl_19[4:0],up_ch_tx_postcursor_19[4:0],up_ch_tx_precursor_19[4:0],up_ch_enb_19,up_ch_addr_19[11:0],up_ch_wr_19,up_ch_wdata_19[15:0],up_ch_rdata_19[15:0],up_ch_ready_19,up_cm_enb_20,up_cm_addr_20[11:0],up_cm_wr_20,up_cm_wdata_20[15:0],up_cm_rdata_20[15:0],up_cm_ready_20,up_es_enb_20,up_es_addr_20[11:0],up_es_wr_20,up_es_reset_20,up_es_wdata_20[15:0],up_es_rdata_20[15:0],up_es_ready_20,up_ch_pll_locked_20,up_ch_rst_20,up_ch_user_ready_20,up_ch_rst_done_20,up_ch_prbsforceerr_20,up_ch_prbssel_20[3:0],up_ch_prbscntreset_20,up_ch_prbserr_20,up_ch_prbslocked_20,up_ch_bufstatus_20[1:0],up_ch_bufstatus_rst_20,up_ch_lpm_dfe_n_20,up_ch_rate_20[2:0],up_ch_sys_clk_sel_20[1:0],up_ch_out_clk_sel_20[2:0],up_ch_tx_diffctrl_20[4:0],up_ch_tx_postcursor_20[4:0],up_ch_tx_precursor_20[4:0],up_ch_enb_20,up_ch_addr_20[11:0],up_ch_wr_20,up_ch_wdata_20[15:0],up_ch_rdata_20[15:0],up_ch_ready_20,up_es_enb_21,up_es_addr_21[11:0],up_es_wr_21,up_es_reset_21,up_es_wdata_21[15:0],up_es_rdata_21[15:0],up_es_ready_21,up_ch_pll_locked_21,up_ch_rst_21,up_ch_user_ready_21,up_ch_rst_done_21,up_ch_prbsforceerr_21,up_ch_prbssel_21[3:0],up_ch_prbscntreset_21,up_ch_prbserr_21,up_ch_prbslocked_21,up_ch_bufstatus_21[1:0],up_ch_bufstatus_rst_21,up_ch_lpm_dfe_n_21,up_ch_rate_21[2:0],up_ch_sys_clk_sel_21[1:0],up_ch_out_clk_sel_21[2:0],up_ch_tx_diffctrl_21[4:0],up_ch_tx_postcursor_21[4:0],up_ch_tx_precursor_21[4:0],up_ch_enb_21,up_ch_addr_21[11:0],up_ch_wr_21,up_ch_wdata_21[15:0],up_ch_rdata_21[15:0],up_ch_ready_21,up_es_enb_22,up_es_addr_22[11:0],up_es_wr_22,up_es_reset_22,up_es_wdata_22[15:0],up_es_rdata_22[15:0],up_es_ready_22,up_ch_pll_locked_22,up_ch_rst_22,up_ch_user_ready_22,up_ch_rst_done_22,up_ch_prbsforceerr_22,up_ch_prbssel_22[3:0],up_ch_prbscntreset_22,up_ch_prbserr_22,up_ch_prbslocked_22,up_ch_bufstatus_22[1:0],up_ch_bufstatus_rst_22,up_ch_lpm_dfe_n_22,up_ch_rate_22[2:0],up_ch_sys_clk_sel_22[1:0],up_ch_out_clk_sel_22[2:0],up_ch_tx_diffctrl_22[4:0],up_ch_tx_postcursor_22[4:0],up_ch_tx_precursor_22[4:0],up_ch_enb_22,up_ch_addr_22[11:0],up_ch_wr_22,up_ch_wdata_22[15:0],up_ch_rdata_22[15:0],up_ch_ready_22,up_es_enb_23,up_es_addr_23[11:0],up_es_wr_23,up_es_reset_23,up_es_wdata_23[15:0],up_es_rdata_23[15:0],up_es_ready_23,up_ch_pll_locked_23,up_ch_rst_23,up_ch_user_ready_23,up_ch_rst_done_23,up_ch_prbsforceerr_23,up_ch_prbssel_23[3:0],up_ch_prbscntreset_23,up_ch_prbserr_23,up_ch_prbslocked_23,up_ch_bufstatus_23[1:0],up_ch_bufstatus_rst_23,up_ch_lpm_dfe_n_23,up_ch_rate_23[2:0],up_ch_sys_clk_sel_23[1:0],up_ch_out_clk_sel_23[2:0],up_ch_tx_diffctrl_23[4:0],up_ch_tx_postcursor_23[4:0],up_ch_tx_precursor_23[4:0],up_ch_enb_23,up_ch_addr_23[11:0],up_ch_wr_23,up_ch_wdata_23[15:0],up_ch_rdata_23[15:0],up_ch_ready_23,up_cm_enb_24,up_cm_addr_24[11:0],up_cm_wr_24,up_cm_wdata_24[15:0],up_cm_rdata_24[15:0],up_cm_ready_24,up_es_enb_24,up_es_addr_24[11:0],up_es_wr_24,up_es_reset_24,up_es_wdata_24[15:0],up_es_rdata_24[15:0],up_es_ready_24,up_ch_pll_locked_24,up_ch_rst_24,up_ch_user_ready_24,up_ch_rst_done_24,up_ch_prbsforceerr_24,up_ch_prbssel_24[3:0],up_ch_prbscntreset_24,up_ch_prbserr_24,up_ch_prbslocked_24,up_ch_bufstatus_24[1:0],up_ch_bufstatus_rst_24,up_ch_lpm_dfe_n_24,up_ch_rate_24[2:0],up_ch_sys_clk_sel_24[1:0],up_ch_out_clk_sel_24[2:0],up_ch_tx_diffctrl_24[4:0],up_ch_tx_postcursor_24[4:0],up_ch_tx_precursor_24[4:0],up_ch_enb_24,up_ch_addr_24[11:0],up_ch_wr_24,up_ch_wdata_24[15:0],up_ch_rdata_24[15:0],up_ch_ready_24,up_es_enb_25,up_es_addr_25[11:0],up_es_wr_25,up_es_reset_25,up_es_wdata_25[15:0],up_es_rdata_25[15:0],up_es_ready_25,up_ch_pll_locked_25,up_ch_rst_25,up_ch_user_ready_25,up_ch_rst_done_25,up_ch_prbsforceerr_25,up_ch_prbssel_25[3:0],up_ch_prbscntreset_25,up_ch_prbserr_25,up_ch_prbslocked_25,up_ch_bufstatus_25[1:0],up_ch_bufstatus_rst_25,up_ch_lpm_dfe_n_25,up_ch_rate_25[2:0],up_ch_sys_clk_sel_25[1:0],up_ch_out_clk_sel_25[2:0],up_ch_tx_diffctrl_25[4:0],up_ch_tx_postcursor_25[4:0],up_ch_tx_precursor_25[4:0],up_ch_enb_25,up_ch_addr_25[11:0],up_ch_wr_25,up_ch_wdata_25[15:0],up_ch_rdata_25[15:0],up_ch_ready_25,up_es_enb_26,up_es_addr_26[11:0],up_es_wr_26,up_es_reset_26,up_es_wdata_26[15:0],up_es_rdata_26[15:0],up_es_ready_26,up_ch_pll_locked_26,up_ch_rst_26,up_ch_user_ready_26,up_ch_rst_done_26,up_ch_prbsforceerr_26,up_ch_prbssel_26[3:0],up_ch_prbscntreset_26,up_ch_prbserr_26,up_ch_prbslocked_26,up_ch_bufstatus_26[1:0],up_ch_bufstatus_rst_26,up_ch_lpm_dfe_n_26,up_ch_rate_26[2:0],up_ch_sys_clk_sel_26[1:0],up_ch_out_clk_sel_26[2:0],up_ch_tx_diffctrl_26[4:0],up_ch_tx_postcursor_26[4:0],up_ch_tx_precursor_26[4:0],up_ch_enb_26,up_ch_addr_26[11:0],up_ch_wr_26,up_ch_wdata_26[15:0],up_ch_rdata_26[15:0],up_ch_ready_26,up_es_enb_27,up_es_addr_27[11:0],up_es_wr_27,up_es_reset_27,up_es_wdata_27[15:0],up_es_rdata_27[15:0],up_es_ready_27,up_ch_pll_locked_27,up_ch_rst_27,up_ch_user_ready_27,up_ch_rst_done_27,up_ch_prbsforceerr_27,up_ch_prbssel_27[3:0],up_ch_prbscntreset_27,up_ch_prbserr_27,up_ch_prbslocked_27,up_ch_bufstatus_27[1:0],up_ch_bufstatus_rst_27,up_ch_lpm_dfe_n_27,up_ch_rate_27[2:0],up_ch_sys_clk_sel_27[1:0],up_ch_out_clk_sel_27[2:0],up_ch_tx_diffctrl_27[4:0],up_ch_tx_postcursor_27[4:0],up_ch_tx_precursor_27[4:0],up_ch_enb_27,up_ch_addr_27[11:0],up_ch_wr_27,up_ch_wdata_27[15:0],up_ch_rdata_27[15:0],up_ch_ready_27,up_cm_enb_28,up_cm_addr_28[11:0],up_cm_wr_28,up_cm_wdata_28[15:0],up_cm_rdata_28[15:0],up_cm_ready_28,up_es_enb_28,up_es_addr_28[11:0],up_es_wr_28,up_es_reset_28,up_es_wdata_28[15:0],up_es_rdata_28[15:0],up_es_ready_28,up_ch_pll_locked_28,up_ch_rst_28,up_ch_user_ready_28,up_ch_rst_done_28,up_ch_prbsforceerr_28,up_ch_prbssel_28[3:0],up_ch_prbscntreset_28,up_ch_prbserr_28,up_ch_prbslocked_28,up_ch_bufstatus_28[1:0],up_ch_bufstatus_rst_28,up_ch_lpm_dfe_n_28,up_ch_rate_28[2:0],up_ch_sys_clk_sel_28[1:0],up_ch_out_clk_sel_28[2:0],up_ch_tx_diffctrl_28[4:0],up_ch_tx_postcursor_28[4:0],up_ch_tx_precursor_28[4:0],up_ch_enb_28,up_ch_addr_28[11:0],up_ch_wr_28,up_ch_wdata_28[15:0],up_ch_rdata_28[15:0],up_ch_ready_28,up_es_enb_29,up_es_addr_29[11:0],up_es_wr_29,up_es_reset_29,up_es_wdata_29[15:0],up_es_rdata_29[15:0],up_es_ready_29,up_ch_pll_locked_29,up_ch_rst_29,up_ch_user_ready_29,up_ch_rst_done_29,up_ch_prbsforceerr_29,up_ch_prbssel_29[3:0],up_ch_prbscntreset_29,up_ch_prbserr_29,up_ch_prbslocked_29,up_ch_bufstatus_29[1:0],up_ch_bufstatus_rst_29,up_ch_lpm_dfe_n_29,up_ch_rate_29[2:0],up_ch_sys_clk_sel_29[1:0],up_ch_out_clk_sel_29[2:0],up_ch_tx_diffctrl_29[4:0],up_ch_tx_postcursor_29[4:0],up_ch_tx_precursor_29[4:0],up_ch_enb_29,up_ch_addr_29[11:0],up_ch_wr_29,up_ch_wdata_29[15:0],up_ch_rdata_29[15:0],up_ch_ready_29,up_es_enb_30,up_es_addr_30[11:0],up_es_wr_30,up_es_reset_30,up_es_wdata_30[15:0],up_es_rdata_30[15:0],up_es_ready_30,up_ch_pll_locked_30,up_ch_rst_30,up_ch_user_ready_30,up_ch_rst_done_30,up_ch_prbsforceerr_30,up_ch_prbssel_30[3:0],up_ch_prbscntreset_30,up_ch_prbserr_30,up_ch_prbslocked_30,up_ch_bufstatus_30[1:0],up_ch_bufstatus_rst_30,up_ch_lpm_dfe_n_30,up_ch_rate_30[2:0],up_ch_sys_clk_sel_30[1:0],up_ch_out_clk_sel_30[2:0],up_ch_tx_diffctrl_30[4:0],up_ch_tx_postcursor_30[4:0],up_ch_tx_precursor_30[4:0],up_ch_enb_30,up_ch_addr_30[11:0],up_ch_wr_30,up_ch_wdata_30[15:0],up_ch_rdata_30[15:0],up_ch_ready_30,up_es_enb_31,up_es_addr_31[11:0],up_es_wr_31,up_es_reset_31,up_es_wdata_31[15:0],up_es_rdata_31[15:0],up_es_ready_31,up_ch_pll_locked_31,up_ch_rst_31,up_ch_user_ready_31,up_ch_rst_done_31,up_ch_prbsforceerr_31,up_ch_prbssel_31[3:0],up_ch_prbscntreset_31,up_ch_prbserr_31,up_ch_prbslocked_31,up_ch_bufstatus_31[1:0],up_ch_bufstatus_rst_31,up_ch_lpm_dfe_n_31,up_ch_rate_31[2:0],up_ch_sys_clk_sel_31[1:0],up_ch_out_clk_sel_31[2:0],up_ch_tx_diffctrl_31[4:0],up_ch_tx_postcursor_31[4:0],up_ch_tx_precursor_31[4:0],up_ch_enb_31,up_ch_addr_31[11:0],up_ch_wr_31,up_ch_wdata_31[15:0],up_ch_rdata_31[15:0],up_ch_ready_31,s_axi_aclk,s_axi_aresetn,up_status,up_pll_rst,s_axi_awvalid,s_axi_awaddr[15:0],s_axi_awprot[2:0],s_axi_awready,s_axi_wvalid,s_axi_wdata[31:0],s_axi_wstrb[3:0],s_axi_wready,s_axi_bvalid,s_axi_bresp[1:0],s_axi_bready,s_axi_arvalid,s_axi_araddr[15:0],s_axi_arprot[2:0],s_axi_arready,s_axi_rvalid,s_axi_rresp[1:0],s_axi_rdata[31:0],s_axi_rready,m_axi_awvalid,m_axi_awaddr[31:0],m_axi_awprot[2:0],m_axi_awready,m_axi_wvalid,m_axi_wdata[31:0],m_axi_wstrb[3:0],m_axi_wready,m_axi_bvalid,m_axi_bresp[1:0],m_axi_bready,m_axi_arvalid,m_axi_araddr[31:0],m_axi_arprot[2:0],m_axi_arready,m_axi_rvalid,m_axi_rdata[31:0],m_axi_rresp[1:0],m_axi_rready";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "axi_adxcvr,Vivado 2022.2";
begin
end;
