# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_ad9860_tpl/axi_ad9860_tpl.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9860_tpl || ORIG_REF_NAME==axi_ad9860_tpl} -quiet] -quiet

# IP: bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0 || ORIG_REF_NAME==axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0} -quiet] -quiet

# IP: bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_xlslice_0_0/axi_ad9860_tpl_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9860_tpl_xlslice_0_0 || ORIG_REF_NAME==axi_ad9860_tpl_xlslice_0_0} -quiet] -quiet

# IP: bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_enable_xlslice_0_0/axi_ad9860_tpl_enable_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9860_tpl_enable_xlslice_0_0 || ORIG_REF_NAME==axi_ad9860_tpl_enable_xlslice_0_0} -quiet] -quiet

# IP: bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_enable_xlslice_0_1/axi_ad9860_tpl_enable_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9860_tpl_enable_xlslice_0_1 || ORIG_REF_NAME==axi_ad9860_tpl_enable_xlslice_0_1} -quiet] -quiet

# IP: bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_valid_xlslice_0_0/axi_ad9860_tpl_valid_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9860_tpl_valid_xlslice_0_0 || ORIG_REF_NAME==axi_ad9860_tpl_valid_xlslice_0_0} -quiet] -quiet

# IP: bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_enable_xlslice_0_2/axi_ad9860_tpl_enable_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9860_tpl_enable_xlslice_0_2 || ORIG_REF_NAME==axi_ad9860_tpl_enable_xlslice_0_2} -quiet] -quiet

# IP: bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_data_xlslice_0_0/axi_ad9860_tpl_data_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9860_tpl_data_xlslice_0_0 || ORIG_REF_NAME==axi_ad9860_tpl_data_xlslice_0_0} -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/axi_ad9860_tpl_ooc.xdc
