# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_ad9680_jesd/axi_ad9680_jesd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9680_jesd || ORIG_REF_NAME==axi_ad9680_jesd} -quiet] -quiet

# IP: bd/axi_ad9680_jesd/ip/axi_ad9680_jesd_axi_jesd204_rx_0_0/axi_ad9680_jesd_axi_jesd204_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9680_jesd_axi_jesd204_rx_0_0 || ORIG_REF_NAME==axi_ad9680_jesd_axi_jesd204_rx_0_0} -quiet] -quiet

# IP: bd/axi_ad9680_jesd/ip/axi_ad9680_jesd_jesd204_rx_0_0/axi_ad9680_jesd_jesd204_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_ad9680_jesd_jesd204_rx_0_0 || ORIG_REF_NAME==axi_ad9680_jesd_jesd204_rx_0_0} -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_jesd/axi_ad9680_jesd.gen/sources_1/bd/axi_ad9680_jesd/axi_ad9680_jesd_ooc.xdc
