# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0.xci
# IP: The module: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/ad_rst_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/up_clock_mon_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/up_xfer_cntrl_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/up_xfer_status_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0.xci
# IP: The module: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/ad_rst_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/up_clock_mon_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/up_xfer_cntrl_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/axi_ad9680_tpl/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/up_xfer_status_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
