# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/phy_shared/phy_shared.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared || ORIG_REF_NAME==phy_shared} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_axi_adxcvr_0_0/phy_shared_axi_adxcvr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_axi_adxcvr_0_0 || ORIG_REF_NAME==phy_shared_axi_adxcvr_0_0} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_axi_adxcvr_0_1/phy_shared_axi_adxcvr_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_axi_adxcvr_0_1 || ORIG_REF_NAME==phy_shared_axi_adxcvr_0_1} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_util_adxcvr_0_0/phy_shared_util_adxcvr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_util_adxcvr_0_0 || ORIG_REF_NAME==phy_shared_util_adxcvr_0_0} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlconcat_0_0/phy_shared_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlconcat_0_0 || ORIG_REF_NAME==phy_shared_xlconcat_0_0} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlconcat_0_1/phy_shared_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlconcat_0_1 || ORIG_REF_NAME==phy_shared_xlconcat_0_1} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlconcat_0_2/phy_shared_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlconcat_0_2 || ORIG_REF_NAME==phy_shared_xlconcat_0_2} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlconcat_0_3/phy_shared_xlconcat_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlconcat_0_3 || ORIG_REF_NAME==phy_shared_xlconcat_0_3} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlconcat_0_4/phy_shared_xlconcat_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlconcat_0_4 || ORIG_REF_NAME==phy_shared_xlconcat_0_4} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlconcat_0_5/phy_shared_xlconcat_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlconcat_0_5 || ORIG_REF_NAME==phy_shared_xlconcat_0_5} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_0_0/phy_shared_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_0_0 || ORIG_REF_NAME==phy_shared_xlslice_0_0} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_charisk_0_0/phy_shared_xlslice_charisk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_charisk_0_0 || ORIG_REF_NAME==phy_shared_xlslice_charisk_0_0} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_charisk_0_1/phy_shared_xlslice_charisk_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_charisk_0_1 || ORIG_REF_NAME==phy_shared_xlslice_charisk_0_1} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_charisk_0_2/phy_shared_xlslice_charisk_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_charisk_0_2 || ORIG_REF_NAME==phy_shared_xlslice_charisk_0_2} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_0_1/phy_shared_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_0_1 || ORIG_REF_NAME==phy_shared_xlslice_0_1} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_header_0_0/phy_shared_xlslice_header_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_header_0_0 || ORIG_REF_NAME==phy_shared_xlslice_header_0_0} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_header_0_1/phy_shared_xlslice_header_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_header_0_1 || ORIG_REF_NAME==phy_shared_xlslice_header_0_1} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_header_0_2/phy_shared_xlslice_header_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_header_0_2 || ORIG_REF_NAME==phy_shared_xlslice_header_0_2} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_0_2/phy_shared_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_0_2 || ORIG_REF_NAME==phy_shared_xlslice_0_2} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_data_0_0/phy_shared_xlslice_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_data_0_0 || ORIG_REF_NAME==phy_shared_xlslice_data_0_0} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_data_0_1/phy_shared_xlslice_data_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_data_0_1 || ORIG_REF_NAME==phy_shared_xlslice_data_0_1} -quiet] -quiet

# IP: bd/phy_shared/ip/phy_shared_xlslice_data_0_2/phy_shared_xlslice_data_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phy_shared_xlslice_data_0_2 || ORIG_REF_NAME==phy_shared_xlslice_data_0_2} -quiet] -quiet

# XDC: c:/GitHub/jesd204/layers/phy_shared/phy_shared.gen/sources_1/bd/phy_shared/phy_shared_ooc.xdc
