#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : jesd204b.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Nov 07 13:53:12 -0300 2024
# SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: jesd204b.sh [-help]
# usage: jesd204b.sh [-lib_map_path]
# usage: jesd204b.sh [-noclean_files]
# usage: jesd204b.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'jesd204b.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_13 zynq_ultra_ps_e_vip_v1_0_13 xil_defaultlib xlconstant_v1_1_7 xlconcat_v2_1_4 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_27 fifo_generator_v13_2_7 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xlslice_v1_0_2 lib_pkg_v1_0_2 lib_fifo_v1_0_16 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_29 axi_sg_v4_1_15 axi_dma_v7_1_28 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_29 axi_protocol_converter_v2_1_27 axi_clock_converter_v2_1_26 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "jesd204b.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_zynq_ultra_ps_e_0_0/sim/jesd204b_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_xlconstant_0_0/sim/jesd204b_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_xlconcat_0_0/sim/jesd204b_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_xbar_0/sim/jesd204b_xbar_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_xbar_1/sim/jesd204b_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_proc_sys_reset_0_0/sim/jesd204b_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_proc_sys_reset_0_1/sim/jesd204b_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/393c/axi_adxcvr_es.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/393c/axi_adxcvr_mdrp.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/393c/axi_adxcvr_mstatus.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/393c/axi_adxcvr_up.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/393c/up_axi.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/393c/axi_adxcvr.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_axi_adxcvr_0_0/sim/phy_shared_axi_adxcvr_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_axi_adxcvr_0_1/sim/phy_shared_axi_adxcvr_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/07df/sync_bits.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/07df/sync_header_align.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/07df/util_adxcvr_xch.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/07df/util_adxcvr_xcm.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/07df/util_adxcvr.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_util_adxcvr_0_0/sim/phy_shared_util_adxcvr_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlconcat_0_0/sim/phy_shared_xlconcat_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlconcat_0_1/sim/phy_shared_xlconcat_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlconcat_0_2/sim/phy_shared_xlconcat_0_2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlconcat_0_3/sim/phy_shared_xlconcat_0_3.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlconcat_0_4/sim/phy_shared_xlconcat_0_4.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlconcat_0_5/sim/phy_shared_xlconcat_0_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_0_0/sim/phy_shared_xlslice_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_charisk_0_0/sim/phy_shared_xlslice_charisk_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_charisk_0_1/sim/phy_shared_xlslice_charisk_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_charisk_0_2/sim/phy_shared_xlslice_charisk_0_2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_0_1/sim/phy_shared_xlslice_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_header_0_0/sim/phy_shared_xlslice_header_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_header_0_1/sim/phy_shared_xlslice_header_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_header_0_2/sim/phy_shared_xlslice_header_0_2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_0_2/sim/phy_shared_xlslice_0_2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_data_0_0/sim/phy_shared_xlslice_data_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_data_0_1/sim/phy_shared_xlslice_data_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/phy_shared.srcs/sources_1/bd/phy_shared/ip/phy_shared_xlslice_data_0_2/sim/phy_shared_xlslice_data_0_2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/e38e/phy_shared.gen/sources_1/bd/phy_shared/sim/phy_shared.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/e38e/phy_shared.gen/sources_1/bd/phy_shared/hdl/phy_shared_wrapper.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_phy_shared_0_0/sim/jesd204b_phy_shared_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/jesd204_up_common.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/jesd204_up_ilas_mem.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/jesd204_up_rx.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/jesd204_up_rx_lane.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/jesd204_up_sysref.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/sync_data.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/sync_event.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/up_clock_mon.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/6992/axi_jesd204_rx.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ip/axi_ad9680_jesd_axi_jesd204_rx_0_0/sim/axi_ad9680_jesd_axi_jesd204_rx_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/align_mux.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/elastic_buffer.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/error_monitor.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_crc12.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_frame_align_replace.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_frame_mark.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_ilas_monitor.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_lane_latency_monitor.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_lmfc.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_rx_cgs.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_rx_ctrl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_rx_ctrl_64b.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_rx_frame_align.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_rx_header.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_rx_lane.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_rx_lane_64b.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_scrambler.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_scrambler_64b.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/pipeline_stage.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ipshared/0f16/jesd204_rx.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/axi_ad9680_jesd.srcs/sources_1/bd/axi_ad9680_jesd/ip/axi_ad9680_jesd_jesd204_rx_0_0/sim/axi_ad9680_jesd_jesd204_rx_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/4573/axi_ad9680_jesd.gen/sources_1/bd/axi_ad9680_jesd/sim/axi_ad9680_jesd.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/4573/axi_ad9680_jesd.gen/sources_1/bd/axi_ad9680_jesd/hdl/axi_ad9680_jesd_wrapper.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_jesd_0_0/sim/jesd204b_axi_ad9680_jesd_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_proc_sys_reset_0_2/sim/jesd204b_proc_sys_reset_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_xlconcat_0_1/sim/jesd204b_xlconcat_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/ad_mem_asym.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/address_generator.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac_burst_memory.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac_regmap.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac_regmap_request.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac_reset_manager.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac_resize_dest.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac_resize_src.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac_response_manager.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac_transfer.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_register_slice.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/data_mover.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/dest_axi_mm.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/dest_axi_stream.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/dest_fifo_inf.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/dmac_2d_transfer.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/dmac_sg.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/request_arb.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/request_generator.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/response_generator.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/response_handler.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/splitter.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/src_axi_mm.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/src_axi_stream.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/src_fifo_inf.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/sync_gray.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/util_axis_fifo.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/util_axis_fifo_address_generator.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7/axi_dmac.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_dmac_0_1/sim/jesd204b_axi_dmac_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6649/ad_perfect_shuffle.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6649/pack_ctrl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6649/pack_interconnect.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6649/pack_network.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6649/pack_shell.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6649/util_cpack2_impl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6649/util_cpack2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_util_cpack2_0_0/sim/jesd204b_util_cpack2_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/b2b8/ad_mem.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/b2b8/util_do_ram.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_util_do_ram_0_0/sim/jesd204b_util_do_ram_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/7831/data_offload_fsm.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/7831/data_offload_regmap.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/7831/util_axis_fifo_asym.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/7831/data_offload.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_data_offload_0_0/sim/jesd204b_data_offload_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_xlconstant_0_1/sim/jesd204b_xlconstant_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_datafmt.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_ip_jesd204_tpl_adc_channel.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_ip_jesd204_tpl_adc_core.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_ip_jesd204_tpl_adc_deframer.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_ip_jesd204_tpl_adc_pnmon.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_ip_jesd204_tpl_adc_regmap.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_pnmon.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_rst.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_xcvr_rx_if.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/up_adc_channel.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/up_adc_common.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/up_axi.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/up_clock_mon.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/up_tpl_common.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/up_xfer_cntrl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/up_xfer_status.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/util_ext_sync.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ipshared/fafe/ad_ip_jesd204_tpl_adc.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0/sim/axi_ad9860_tpl_ad_ip_jesd204_tpl_adc_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_xlslice_0_0/sim/axi_ad9860_tpl_xlslice_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_enable_xlslice_0_0/sim/axi_ad9860_tpl_enable_xlslice_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_enable_xlslice_0_1/sim/axi_ad9860_tpl_enable_xlslice_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_valid_xlslice_0_0/sim/axi_ad9860_tpl_valid_xlslice_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_enable_xlslice_0_2/sim/axi_ad9860_tpl_enable_xlslice_0_2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/axi_ad9680_tpl.srcs/sources_1/bd/axi_ad9860_tpl/ip/axi_ad9860_tpl_data_xlslice_0_0/sim/axi_ad9860_tpl_data_xlslice_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/2364/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/sim/axi_ad9860_tpl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/2364/axi_ad9680_tpl.gen/sources_1/bd/axi_ad9860_tpl/hdl/axi_ad9860_tpl_wrapper.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9680_tpl_0_0/sim/jesd204b_axi_ad9680_tpl_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_xlconcat_0_2/sim/jesd204b_xlconcat_0_2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/960d/util_upack2_impl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/960d/util_upack2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_util_upack2_0_0/sim/jesd204b_util_upack2_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_dds.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_dds_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_dds_2.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_dds_cordic_pipe.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_dds_sine.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_dds_sine_cordic.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_ip_jesd204_tpl_dac_channel.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_ip_jesd204_tpl_dac_core.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_ip_jesd204_tpl_dac_framer.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_ip_jesd204_tpl_dac_pn.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_ip_jesd204_tpl_dac_regmap.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_iqcor.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_mul.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_mux.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_mux_core.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_rst.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/up_dac_channel.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/up_dac_common.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/up_tpl_common.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/up_xfer_cntrl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/up_xfer_status.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/util_ext_sync.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ipshared/c64d/ad_ip_jesd204_tpl_dac.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ip/axi_ad9144_tpl_ad_ip_jesd204_tpl_dac_0_0/sim/axi_ad9144_tpl_ad_ip_jesd204_tpl_dac_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ip/axi_ad9144_tpl_xlconcat_0_0/sim/axi_ad9144_tpl_xlconcat_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ip/axi_ad9144_tpl_xlslice_0_0/sim/axi_ad9144_tpl_xlslice_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ip/axi_ad9144_tpl_enable_xlslice_0_0/sim/axi_ad9144_tpl_enable_xlslice_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ip/axi_ad9144_tpl_enable_xlslice_0_1/sim/axi_ad9144_tpl_enable_xlslice_0_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/axi_ad9144_tpl.srcs/sources_1/bd/axi_ad9144_tpl/ip/axi_ad9144_tpl_valid_xlslice_0_0/sim/axi_ad9144_tpl_valid_xlslice_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6df6/axi_ad9144_tpl.gen/sources_1/bd/axi_ad9144_tpl/sim/axi_ad9144_tpl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6df6/axi_ad9144_tpl.gen/sources_1/bd/axi_ad9144_tpl/hdl/axi_ad9144_tpl_wrapper.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_tpl_0_0/sim/jesd204b_axi_ad9144_tpl_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/c03d/jesd204_up_tx.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/c03d/axi_jesd204_tx.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ip/axi_ad9144_jesd_axi_jesd204_tx_0_0/sim/axi_ad9144_jesd_axi_jesd204_tx_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/b800/ad_pack.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/b800/ad_upack.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/b800/jesd204_tx_ctrl.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/b800/jesd204_tx_gearbox.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/b800/jesd204_tx_header.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/b800/jesd204_tx_lane.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/b800/jesd204_tx_lane_64b.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ipshared/b800/jesd204_tx.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/axi_ad9144_jesd.srcs/sources_1/bd/axi_ad9144_jesd/ip/axi_ad9144_jesd_jesd204_tx_0_0/sim/axi_ad9144_jesd_jesd204_tx_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ba8e/axi_ad9144_jesd.gen/sources_1/bd/axi_ad9144_jesd/sim/axi_ad9144_jesd.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ba8e/axi_ad9144_jesd.gen/sources_1/bd/axi_ad9144_jesd/hdl/axi_ad9144_jesd_wrapper.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_ad9144_jesd_0_0/sim/jesd204b_axi_ad9144_jesd_0_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_xlconcat_0_3/sim/jesd204b_xlconcat_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_29 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/2237/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/751a/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_28 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/70c4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_dma_0_0/sim/jesd204b_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_29 $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/6219/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_axi_gpio_0_0/sim/jesd204b_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_counter_ceil_0_0/sim/jesd204b_counter_ceil_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/4675/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ipshared/d0d7" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_auto_ds_0/sim/jesd204b_auto_ds_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_auto_pc_0/sim/jesd204b_auto_pc_0.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_auto_ds_1/sim/jesd204b_auto_ds_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/ip/jesd204b_auto_pc_1/sim/jesd204b_auto_pc_1.v" \
    "$ref_dir/../../../../jesd204b.gen/sources_1/bd/jesd204b/sim/jesd204b.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.jesd204b xil_defaultlib.glbl -o jesd204b_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./jesd204b_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./jesd204b.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key jesd204b_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc jesd204b_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./jesd204b.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: jesd204b.sh [-help]\n\
Usage: jesd204b.sh [-lib_map_path]\n\
Usage: jesd204b.sh [-reset_run]\n\
Usage: jesd204b.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
